CREATE TABLE if not EXISTS `user` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增id',
	`name` VARCHAR(50) NOT NULL DEFAULT '""' COMMENT '用户名',
	`password` VARCHAR(100) NOT NULL DEFAULT '""' COMMENT '密码',
	`ext_info` VARCHAR(2048) NOT NULL DEFAULT '""' COMMENT '扩展信息',
	`created_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`updated_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `name` (`name`)
)
COMMENT='用户信息'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
